import { ref } from 'vue';
import { IAIEntity } from '../type/workbench.type';
import img1 from '../static/1.png';
import img2 from '../static/2.png';

export const useWidget = () => {
  const groupList1 = ref<IAIEntity[]>([
    {
      id: '1',
      persons: [{ id: '2', name: 'Cedric', img: img2 }],
    },
    {
      id: '2',
      persons: [{ id: '1', name: 'Lysander', img: img1 }],
    },
    { id: '3', persons: [] },
    { id: '4', persons: [] },
    { id: '5', persons: [] },
    { id: '6', persons: [] },
    { id: '7', persons: [] },
    { id: '8', persons: [] },
    { id: '9', persons: [] },
    { id: '10', persons: [] },
    { id: '11', persons: [] },
    { id: '12', persons: [] },
    { id: '13', persons: [] },
    { id: '14', persons: [] },
    { id: '15', persons: [] },
    { id: '16', persons: [] },
    { id: '17', persons: [] },
    { id: '18', persons: [] },
    { id: '19', persons: [] },
    { id: '20', persons: [] },
    { id: '21', persons: [] },
    { id: '22', persons: [{ id: '1', name: 'Lysander', img: img1 }] },
    { id: '23', persons: [] },
    { id: '24', persons: [] },
    { id: '25', persons: [] },
    { id: '26', persons: [] },
    { id: '27', persons: [] },
  ]);
  const groupList2 = ref<IAIEntity[]>([
    {
      id: '1',
      persons: [
        { id: '1', name: 'Lysander', img: img1 },
        { id: '2', name: 'Cedric', img: img2 },
      ],
    },
    {
      id: '2',
      persons: [{ id: '1', name: 'Lysander', img: img1 }],
    },
    { id: '3', persons: [] },
    { id: '4', persons: [] },
    { id: '5', persons: [] },
    { id: '6', persons: [] },
    { id: '7', persons: [] },
    { id: '8', persons: [{ id: '1', name: 'Lysander', img: img1 }] },
    { id: '9', persons: [] },
    { id: '10', persons: [] },
    { id: '11', persons: [] },
    { id: '12', persons: [] },
    { id: '13', persons: [] },
    { id: '14', persons: [] },
    { id: '15', persons: [] },
    { id: '16', persons: [] },
    { id: '17', persons: [] },
    { id: '18', persons: [] },
    { id: '19', persons: [] },
    { id: '20', persons: [] },
    { id: '21', persons: [] },
    { id: '22', persons: [] },
    { id: '23', persons: [] },
    { id: '24', persons: [] },
    { id: '25', persons: [] },
    { id: '26', persons: [] },
    { id: '27', persons: [] },
  ]);
  const groupList3 = ref<IAIEntity[]>([
    {
      id: '1',
      persons: [],
    },
    {
      id: '2',
      persons: [{ id: '1', name: 'Lysander', img: img1 }],
    },
    { id: '3', persons: [] },
    { id: '4', persons: [] },
    { id: '5', persons: [] },
    { id: '6', persons: [] },
    { id: '7', persons: [] },
    { id: '8', persons: [] },
    { id: '9', persons: [] },
    { id: '10', persons: [] },
    { id: '11', persons: [] },
    { id: '12', persons: [] },
    { id: '13', persons: [] },
    { id: '14', persons: [] },
    { id: '15', persons: [] },
    { id: '16', persons: [{ id: '1', name: 'Lysander', img: img1 }] },
    { id: '17', persons: [] },
    { id: '18', persons: [] },
    { id: '19', persons: [] },
    { id: '20', persons: [] },
    { id: '21', persons: [] },
    { id: '22', persons: [] },
    { id: '23', persons: [] },
    { id: '24', persons: [] },
    { id: '25', persons: [] },
    { id: '26', persons: [] },
    {
      id: '27',
      persons: [
        { id: '1', name: 'Lysander', img: img1 },
        { id: '2', name: 'Cedric', img: img2 },
      ],
    },
  ]);
  return {
    groupList1,
    groupList2,
    groupList3,
  };
};
